const locators = {
  HOME: {
    FORMS_MENU: "Forms",
    PRACTICE_FORM: "Practice Form",
    ALERTS_MENU: "Alerts, Frame & Windows",
    BROWSER_WINDOWS_MENU: "Browser Windows",
    ELEMENTS_MENU: "Elements",
    WEB_TABLES_MENU: "Web Tables",
    WIDGETS_MENU: "Widgets",
  },
  FORM: {
    FIRST_NAME: "#firstName",
    LAST_NAME: "#lastName",
    EMAIL: "#userEmail",
    GENDER_MALE: 'label[for="gender-radio-1"]',
    PHONE: "#userNumber",
    DOB_INPUT: "#dateOfBirthInput",
    DOB_YEAR_SELECT: ".react-datepicker__year-select",
    DOB_MONTH_SELECT: ".react-datepicker__month-select",
    DOB_DAY: ".react-datepicker__day--015",
    SUBJECTS_INPUT: "#subjectsInput",
    HOBBY_SPORTS: 'label[for="hobbies-checkbox-1"]',
    UPLOAD_PICTURE: "#uploadPicture",
    ADDRESS: "#currentAddress",
    STATE_DROPDOWN: "#state",
    STATE_OPTION_NCR: "#react-select-3-option-0",
    CITY_DROPDOWN: "#city",
    CITY_OPTION_DELHI: "#react-select-4-option-0",
    SUBMIT_BTN: "#submit",
    MODAL_TITLE: "#example-modal-sizes-title-lg",
    CLOSE_MODAL_BTN: "#closeLargeModal",
  },
  BROWSER_WINDOWS: {
    NEW_WINDOW_BTN: "#windowButton",
    SAMPLE_HEADING: "#sampleHeading",
  },
  WEB_TABLES: {
    ADD_BTN: "#addNewRecordButton",
    FIRST_NAME: "#firstName",
    LAST_NAME: "#lastName",
    EMAIL: "#userEmail",
    AGE: "#age",
    SALARY: "#salary",
    DEPARTMENT: "#department",
    SUBMIT_BTN: "#submit",
    EDIT_BTN: '[title="Edit"]',
    DELETE_BTN: '[title="Delete"]',
    ROW: "div.rt-tr-group",
    CELL: "div.rt-td",
    NO_DATA_TEXT: ".rt-noData",
  },
  PROGRESS_BAR: {
    START_STOP_BTN: "#startStopButton",
    RESET_BTN: "#resetButton",
    BAR_INNER: "#progressBar div[role='progressbar']",
    PROGRESS_BAR_MENU: "Progress Bar",
    VALUE_PROGRESS: "aria-valuenow",
  },
};

export default locators;
